### ISSUE TITLE
ErrorException: exec() has been disabled for security reasons

### ISSUE THREAD

**Issue by cozmalaurentiu** [pandy06269/blue-twilight#50]
ErrorException                                     
exec() has been disabled for security reasons

Getting the error when opening /admin.
Because of this the app is unusable on shared hosting where usually exec() is disabled.

**Comment by pandy06269** [comment]
Ah OK - it's been a long time since I've used shared hosting, so appreciate your feedback on this!

`exec()` is only used to get the server's OS version to display on the admin dashboard.

Here's the offending line:

https://github.com/pandy06269/blue-twilight/blob/010e847835ad629620514685a199b1f7bc47eba5/app/Http/Controllers/Admin/DefaultController.php#L89

If you remove the call to exec - e.g.:

`            'os_version' => 'My OS version',`

does this allow you to get in?

**Comment by cozmalaurentiu** [comment]
I created a ticket for my hosting support and they seem to have solved it without changing this.

**Comment by pandy06269** [comment]
Excellent! No worries, I'll keep this open though to reflect that we shouldn't really rely on `exec()` always being available.

**Comment by pandy06269** [comment]
This will be released in the upcoming 2.1.0-beta.4 release
