### ISSUE TITLE
"Private album" option is missing from edit album page

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#69]
Option is only displayed on New album page, it should also be available on Edit album.

![private_album](https://user-images.githubusercontent.com/32333032/31135631-4323365e-a86e-11e7-9065-24dc43890978.jpg)

**Comment by pandy06269** [comment]
This is by design.

Prior to v2.0 when there were no detailed permissions controls, the “private album” checkbox was a simple flag that said if you weren’t logged in, you couldn’t access the album.

Since then, the access control is driven by the “permissions” tab and there is no concept of a “private album.” You give access to those who you want to see it, or to nobody so only you can see it.

When you create a new album, if you don’t tick the “private” checkbox the app will add a default set of permissions that allows anonymous users to see and view it.

Therefore there is no “private” flag to edit after an album is created - you just set or unset the relevant permissions.

**Comment by LNT00** [comment]
Sounds good!
