### ISSUE TITLE
"private album" option is not working correctly, admin users can see all albums

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#70]
Selecting it should make an album private, so only the user that created has access to it. Actually all admin users have access to it.
Admin users should not have access to private albums, only to app configuration screens.

![private_album](https://user-images.githubusercontent.com/32333032/31135769-ae3ef784-a86e-11e7-81ae-3a94516d19b9.jpg)

**Comment by pandy06269** [comment]
Can I clarify some terminology here - an admin user and a user who can access the config screens are two different things.

An admin user is someone who you have ticked the “user is an administrator” option against their profile. Admin users bypass ALL security checks. By making someone an administrator, you are telling the system they can see and do anything.

To give people access to the config screens, you create a user group (eg. Admin Users), assign permissions to the group and add the relevant users to the group. You can be granular with permissions so you can say some people can add albums but not manage users. That’s exactly how I’ve set up the demo system so the demo user cannot change the config but can create albums to see the functionality of the app.

The “private album” option does not assign any default permissions to the album so that it is only accessible by the owner unless you tell it otherwise - either with specific permissions (against a user or group) or by an administrator user.

**Comment by LNT00** [comment]
Yes, it's working correctly as you described.
